id             = "box"
name           = "Box"
version        = "0.1.0"
schema_version = 1
authors        = ["ADI Family <team@adi-family.com>"]
description    = "Syntax support for the Box language"
repository     = "https://github.com/adi-family/box"

[grammars.box]
repository = "https://github.com/adi-family/box"
commit     = "fa57b690769affd283bca146199bd1b1cbb886cc"
path       = "grammars/tree-sitter-box"
